// ~~ Generated by mw-config. DO NOT EDIT — modify mw.config.ts and re-run mw-config instead.

import config from '@merrywhether/config/eslint';

export default [
  {
    ignores: [
      '.cache/**',
      'eslint.config.ts',
      'prettier.config.ts',
      '@types',
    ],
  },
  ...config.react,
];
