// ~~ Generated by projen. To modify, edit .projenrc.js and run "pn pj".

import config from '@merrywhether/config/eslint';

export default [
  {
    ignores: [
      '.cache/**',
      'eslint.config.js',
      'prettier.config.js',
      '@types',
    ],
  },
  ...config.react,
];
