// ~~ Generated by projen. To modify, edit .projenrc.js and run "pn pj".

import config from '@merrywhether/config/eslint';
import { includeIgnoreFile } from 'eslint/config';
import { fileURLToPath } from 'node:url';

const gitignorePath = fileURLToPath(new URL('.gitignore', import.meta.url));

export default [
  includeIgnoreFile(gitignorePath),
  {
    ignores: [
      'eslint.config.js',
      'prettier.config.js',
    ],
  },
  ...config.react,
];
