const AGENTS_SECTION_START = '<!-- mw-config:start -->';
const AGENTS_SECTION_END = '<!-- mw-config:end -->';

const AGENTS_SECTION_BODY = `## Config management (@merrywhether/config)

\`mw.config.ts\` is the single source of truth for all tool configuration
(ESLint, TypeScript, Prettier, Renovate, etc.).

Never edit generated files directly — anything with a \`Generated by mw-config\`
header is overwritten on the next synth. Edit \`mw.config.ts\` instead, then run
\`pnpm pj\` to re-synthesize, or \`pnpm mw-config\` to open the interactive TUI.`;

const AGENTS_SECTION = `${AGENTS_SECTION_START}\n${AGENTS_SECTION_BODY}\n${AGENTS_SECTION_END}`;

export function updateAgentsMd(content: string): string {
  const startIdx = content.indexOf(AGENTS_SECTION_START);
  const endIdx = content.indexOf(AGENTS_SECTION_END);

  if (startIdx !== -1 && endIdx !== -1) {
    // Replace the existing managed section
    return (
      content.slice(0, startIdx)
      + AGENTS_SECTION
      + content.slice(endIdx + AGENTS_SECTION_END.length)
    );
  }

  // Append the section, ensuring a newline separator
  const separator =
    content.length > 0 && !content.endsWith('\n') ? '\n\n' : '\n';
  return `${content + separator + AGENTS_SECTION}\n`;
}

export { AGENTS_SECTION };
