import { existsSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { updateAgentsMd } from './agents-md.ts';
import { getGitUserName } from './git-config.ts';
import { detectPackageManager, getSynthCommand } from './pkg-manager.ts';

const MIGRATION_CANDIDATES = [
  '.projenrc.js',
  '.projenrc.mjs',
  'mw.config.js',
  'mw.config.mjs',
];

export interface FirstRunResult {
  agentsMdUpdated: boolean;
  migrations: string[];
  projenrcGenerated: boolean;
}

export function runFirstRun(cwd: string): FirstRunResult {
  const result: FirstRunResult = {
    agentsMdUpdated: false,
    migrations: [],
    projenrcGenerated: false,
  };

  // Migrate old files
  for (const candidate of MIGRATION_CANDIDATES) {
    const filepath = join(cwd, candidate);
    if (existsSync(filepath)) {
      renameSync(filepath, `${filepath}.old`);
      result.migrations.push(candidate);
    }
  }

  // Detect package manager and generate files
  const pm = detectPackageManager(cwd);
  const synthCommand = getSynthCommand(pm);
  const copyright = getGitUserName();

  // Write mw.config.ts
  writeFileSync(
    join(cwd, 'mw.config.ts'),
    generateMwConfigTs(copyright),
    'utf-8',
  );

  // Write .projenrc.ts
  writeFileSync(
    join(cwd, '.projenrc.ts'),
    generateProjenrcTs(synthCommand),
    'utf-8',
  );
  result.projenrcGenerated = true;

  // Update AGENTS.md
  const agentsMdPath = join(cwd, 'AGENTS.md');
  const existing =
    existsSync(agentsMdPath) ? readFileSync(agentsMdPath, 'utf-8') : '';
  const updated = updateAgentsMd(existing);
  writeFileSync(agentsMdPath, updated, 'utf-8');
  result.agentsMdUpdated = true;

  return result;
}

function generateMwConfigTs(copyright: string): string {
  const copyrightValue = copyright || '{{copyright}}';
  return `import { defineConfig } from '@merrywhether/config';

export default defineConfig({
  project: {
    copyright: '${copyrightValue}',
    depManagement: { tool: null },
    formatting: { tool: 'prettier' },
    license: 'MIT',
    linting: { presets: ['typescript'], tool: 'eslint' },
    typecheck: { presets: ['base'], tool: 'typescript' },
  },
});
`;
}

function generateProjenrcTs(synthCommand: string): string {
  return `// ~~ Generated by mw-config. Edit mw.config.ts instead.
import { readFileSync } from 'node:fs';

import config from './mw.config.ts';
import { MwProject } from '@merrywhether/config';

const { name } = JSON.parse(readFileSync('./package.json', 'utf-8')) as { name: string };
new MwProject({ ...config.project, name }).synth();
// Run: ${synthCommand}
`;
}
