export function generateSkillFile(synthCommand: string): string {
  return `# mw-config skill

## Overview

Projects using \`@merrywhether/config\` are configured through \`mw.config.ts\`.

## Key rules

1. NEVER edit generated files (they have \`Generated by mw-config\` headers)
2. ALWAYS edit \`mw.config.ts\` for config changes
3. After editing \`mw.config.ts\`, run \`${synthCommand}\` to re-synthesize
4. Use \`mw-config --describe\` to see the current parsed config

## Schema

\`mw.config.ts\` uses the \`defineConfig\` helper from \`@merrywhether/config\`:

\`\`\`typescript
import { defineConfig } from '@merrywhether/config';

export default defineConfig({
  project: {
    linting: { tool: 'eslint', presets: ['typescript'] },
    formatting: { tool: 'prettier' },
    depManagement: { tool: null },
    typecheck: { tool: 'typescript', presets: ['base'] },
    license: 'MIT',
    copyright: 'Your Name',
  },
});
\`\`\`

## Workflow

- Edit \`mw.config.ts\`
- Run \`${synthCommand}\` to apply changes
- Commit both \`mw.config.ts\` and any updated generated files
`;
}
