name: Auto Approval

on:
  pull_request:
    types:
      - opened
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: 'check author'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    timeout-minutes: 5

    steps:
      - name: Approve if author is me
        id: check_author
        if: ${{ github.event.pull_request.user.login == 'merrywhether' }}
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: 'APPROVE',
              body: '😶‍🌫️'
            })
