name: Dependency Upgrade

on:
  push:
    branches: [renovate/**]

jobs:
  check:
    name: 'dedupe deps'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          # https://medium.com/prompt/trigger-another-github-workflow-without-using-a-personal-access-token-f594c21373ef
          ssh-key: ${{ secrets.COMMIT_KEY }}
        # https://github.com/marketplace/actions/setup-node-js-environment
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Setup Node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          cache: 'pnpm'
          node-version: '22.14.0'
      - name: Install
        run: pnpm install --ignore-scripts --frozen-lockfile
      - name: Dedupe
        run: pnpm dedupe
      - name: Commit Changes
        run: |
          git config user.name mergewhether
          git config user.email bot@risto.io
          git commit -am "Upgrade transitive dependencies" || exit 0
          git push
          exit 1
