name: Dependency Upgrade

on:
  push:
    branches: [renovate/**]

jobs:
  Check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          # https://medium.com/prompt/trigger-another-github-workflow-without-using-a-personal-access-token-f594c21373ef
          ssh-key: ${{ secrets.COMMIT_KEY }}
        # https://github.com/marketplace/actions/setup-node-js-environment
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: false
      - name: Setup Node + caching
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install
        run: pnpm install --ignore-scripts --frozen-lockfile
      - name: Dedupe
        run: pnpm dedupe
      - name: Commit Changes
        run: |
          git config user.name mergewhether
          git config user.email bot@risto.io
          git commit -am "Upgrade transitive dependencies" || exit 0
          git push
          exit 1
