name: Dependabot

on:
  pull_request:
    branches:
      - dependabot/**
  push:
    branches:
      - dependabot/**

jobs:
  Upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # https://github.com/marketplace/actions/setup-node-js-environment
      - name: Setup yarn caching
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install
        run: yarn install
      - name: Upgrade
        run: yarn upgrade
      - name: Check Diff
        run: |
          git diff-index --quiet HEAD --
          exit $?
      - name: No changes
        if: ${{ success() }}
        run: echo "No yarn.lock changes"
      - name: Update Branch
        if: ${{ failure() }}
        run: |
          echo "Committing yarn.lock changes"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Upgrade transitive dependencies"
          git push
  AutoMerge Patch:
    needs: Upgrade
    runs-on: ubuntu-latest
    steps:
      - name: Get Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Auto-merge for Dependabot patch PRs
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
