name: DB Upgrade

on:
  push:
    branches:
      - dependabot/**

jobs:
  Check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # https://github.com/marketplace/actions/setup-node-js-environment
      - name: Setup yarn caching
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install
        run: yarn install
      - name: Upgrade
        run: yarn upgrade
      - name: Check Diff
        id: check_diff
        run: |
          changes=0\
          git diff-index --quiet HEAD -- || changes=$?
          echo "::set-output name=changes::${changes}"
      - name: No changes
        if: ${{ steps.check_diff.outputs.changes == 0 }}
        run: echo "No yarn.lock changes"
      - name: Update Branch
        if: ${{ steps.check_diff.outputs.changes != 0 }}
        with:
          ssh-key: "${{ secrets.COMMIT_KEY }}"
        run: |
          echo "Committing yarn.lock changes"
          git config user.name merrywhether[bot]
          git config user.email bot@risto.io
          git add .
          git commit -m "Upgrade transitive dependencies"
          git push
          exit 1
  Lint:
    needs: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup yarn caching
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install
        run: yarn install
      - name: Lint
        run: yarn lint
