name: Dependency Upgrade

on:
  push:
    branches: [renovate/**]

jobs:
  Info:
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: |
          echo "${{ github.base_ref }} ${{ github.head_ref }} ${{ github.ref }}"
          echo "info"

  Check:
    if: ${{ startsWith(github.head_ref, 'renovate/') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # https://medium.com/prompt/trigger-another-github-workflow-without-using-a-personal-access-token-f594c21373ef
          ssh-key: ${{ secrets.COMMIT_KEY }}
        # https://github.com/marketplace/actions/setup-node-js-environment
      - name: Setup yarn caching
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install
        run: yarn install --ignore-scripts --frozen-lockfile
      - name: Upgrade
        run: yarn upgrade
      - name: Commit Changes
        run: |
          git config user.name mergewhether
          git config user.email bot@risto.io
          git commit -am "Upgrade transitive dependencies" || exit 0
          git push
          exit 1
