name: Lint

on:
  pull_request:
    branches: [main]

jobs:
  Check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and cache
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'yarn'
        run: yarn install
      - name: Lint
        run: yarn lint
