name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: false
      - name: Setup Node + caching
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install
        run: pnpm install
      - name: ESLint
        run: pnpm lint:es
      - name: Prettier
        if: ${{ always() }}
        run: pnpm lint:md
