name: Lint

on:
  push:
    branches-ignore:
      - dependabot/**



jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup yarn caching
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install
        run: yarn install
      - name: Lint
        run: yarn lint
