name: Node Upgrade

on:
  push:
    branches: [renovate/node**]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: "propagate node upgrade"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          # https://medium.com/prompt/trigger-another-github-workflow-without-using-a-personal-access-token-f594c21373ef
          ssh-key: ${{ secrets.COMMIT_KEY }}
      - name: Setup pnpm
        uses: pnpm/action-setup@26f6d4f2c533a43e6b5da0b4a5dd983f98f7b49a # v6
        with:
          run_install: false
      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          cache: "pnpm"
          node-version: "24.15.0"
      - name: Install
        run: pnpm install --ignore-scripts --frozen-lockfile
      - name: Update Node
        run: pnpm pj
      - name: Commit Changes
        run: |
          git config user.name mergewhether
          git config user.email bot@risto.io
          git commit -am "Propagate node upgrade" || exit 0
      - name: Push Changes
        run: |
          # push back to the branch that triggered this workflow
          git push || echo "No changes to push"
