name: Publish

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ssh-key: ${{ secrets.COMMIT_KEY }}
      - name: Setup pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6
        with:
          run_install: false
      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          cache: 'pnpm'
          node-version: '24.15.0'
          registry-url: https://registry.npmjs.org/
      - name: Install
        run: pnpm install
      - name: Bump version
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          VERSION=${TAG#v}
          git config user.name mergewhether
          git config user.email bot@risto.io
          pnpm version $VERSION --no-git-tag-version
          git add package.json
          git commit -m "$VERSION"
          git push origin HEAD:main
          git tag -f $TAG HEAD
          git push origin -f refs/tags/$TAG
      - name: Generate types
        run: pnpm build:types
      - name: Publish
        run: pnpm publish --access public --no-git-checks --provenance
